server:
  port: 8889
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: site.cilicili.backend.controller;
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: default
    - name: 标题2
      locations: classpath:markdown1/*
      group: 用户模块
  basic:
    enable: false
    username: abc
    password: 123
spring:
  cache:
    type: redis
    redis:
      time-to-live: 86400
      key-prefix: CILI

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    master:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 15
      min-idle: 8
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 60
      validation-query: SELECT 1 FROM DUAL
      async-init: true
    slave:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 15
      min-idle: 8
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 60
      validation-query: SELECT 1 FROM DUAL
  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/java
        - src/main/resources
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  data:
    redis:
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-wait: 60000
      host: 8.217.182.161
      timeout: 60000
      connect-timeout: 60000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # call-setters-on-nulls 参数的作用是查询的某一行某一列为null，是否返回
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: "logical_delete"
decorator:
  datasource:
    p6spy:
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger
      logging: slf4j
    ignore-routing-data-sources: true
    datasource-proxy:
      json-format: true
      logging: slf4j
management:
  health:
    db:
      enabled: false







