spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
cilicili:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 360000
#      valid-time: 15
      refresh-at: 3
# 设置单个文件大小
